#!/bin/bash

# Set the source log directory
source_log_directory="/home/ubuntu/.pm2/logs"

# Get the current date stamp
date_stamp=$(date +"%d-%m-%Y")

# Set the destination log directory with date stamp
destination_log_directory="/home/ubuntu/pm2_logs/$date_stamp"

# Get the current hour stamp
hour_stamp=$(date +"%H-%M")

# Create the destination directory if it doesn't exist
mkdir -p "$destination_log_directory" || exit 1

cd "$source_log_directory" || exit 1

# Check if compressed files exist with the hour stamp
if ls "$destination_log_directory"/*"$hour_stamp.log.gz" 1> /dev/null 2>&1; then
  echo "Compressed files with the hour stamp already exist in destination. Skipping compression."
else
  # Compress log files with the current hour stamp and move to the destination directory
  ls -R1 | grep .log | sed -e 's/.log//g' | while IFS= read -r line; do
    if [ -e "$destination_log_directory/$line-$hour_stamp.log.gz" ]; then
      echo "Compressed file $line-$hour_stamp.log.gz already exists in destination. Skipping compression."
    else
      mv "$line.log" "$destination_log_directory/$line-$hour_stamp.log"
      gzip "$destination_log_directory/$line-$hour_stamp.log"
    fi
  done
fi

pm2 flush
pm2 reload all
